// hilsidebars.js

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const winsidebars = {
    api: [
        {
            type: "autogenerated",
            dirName: ".",
        },
    ],
};

module.exports = winsidebars;
